# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_resmlp.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_pac/ --resume resmlp_12_pac_model/resmlp_12_no_dist_pac_16_all_uvb.pth  --batch-size 128 --tag lr8e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 8e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_resmlp.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_pac/ --resume resmlp_12_pac_model/resmlp_12_no_dist_pac_16_all_uvb.pth  --batch-size 128 --tag lr1e-4_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_resmlp.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_pac/ --resume resmlp_12_pac_model/resmlp_12_no_dist_pac_16_all_uvb.pth  --batch-size 128 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_swin_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_pca_all_mimicking/ --resume swin/ffn_output/all_fc_0.5/swin_b/swin_pca_fewshot2_merge_attn_ffn.pth  --batch-size 64 --tag lr1e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.3
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_swin_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_pca_all_mimicking/ --resume swin/ffn_output/all_fc_0.5/swin_b/swin_pca_fewshot2_merge_attn_ffn.pth  --batch-size 64 --tag lr1e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.5
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_swin_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_pca_all_mimicking/ --resume swin/ffn_output/all_fc_0.5/swin_b/swin_pca_fewshot2_merge_attn_ffn.pth  --batch-size 64 --tag lr1e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.1
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_swin_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_pca_all_mimicking/ --resume swin/ffn_output/all_fc_0.5/swin_b/swin_pca_fewshot2_merge_attn_ffn.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.3
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_swin_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_pca_all_mimicking/ --resume swin/ffn_output/all_fc_0.5/swin_b/swin_pca_fewshot2_merge_attn_ffn.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.5
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_swin_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_pca_all_mimicking/ --resume swin/ffn_output/all_fc_0.5/swin_b/swin_pca_fewshot2_merge_attn_ffn.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.1
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_swin_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_pca_all_mimicking/ --resume swin/ffn_output/all_fc_0.5/swin_b/swin_pca_fewshot2_merge_attn_ffn.pth  --batch-size 64 --tag lr5e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.3
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_swin_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_pca_all_mimicking/ --resume swin/ffn_output/all_fc_0.5/swin_b/swin_pca_fewshot2_merge_attn_ffn.pth  --batch-size 64 --tag lr5e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.5
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_swin_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_pca_all_mimicking/ --resume swin/ffn_output/all_fc_0.5/swin_b/swin_pca_fewshot2_merge_attn_ffn.pth  --batch-size 64 --tag lr5e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.1



# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12342  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pac_16_all_uvb_merge_wo_lastblock.pth  --batch-size 64 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12342  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pac_16_all_uvb_merge_wo_lastblock.pth  --batch-size 64 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12342  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pac_16_all_uvb_merge_wo_lastblock.pth  --batch-size 64 --tag lr1e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_resmlp_adaptive.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_pac_adaptive/ --resume resmlp_12_pac_model/resmlp_12_no_dist_pac_16_all_uvb_adaptive_0.99.pth  --batch-size 128 --tag lr8e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 8e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_resmlp_adaptive.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_pac_adaptive/ --resume resmlp_12_pac_model/resmlp_12_no_dist_pac_16_all_uvb_adaptive_0.99.pth  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_resmlp_adaptive.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_pac_adaptive/ --resume resmlp_12_pac_model/resmlp_12_no_dist_pac_16_all_uvb_adaptive_0.99.pth  --batch-size 128 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_resmlp_adaptive.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_pac_adaptive/ --resume resmlp_12_pac_model/resmlp_12_no_dist_pac_16_all_uvb_adaptive_0.99.pth  --batch-size 128 --tag lr1e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none

# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12340 main.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output checkpoint_baseline/ --batch-szie 256 --opts TRAIN.EPOCHS 50 TRAIN.WARMUP_EPOCHS 5
# sleep 7.8h
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_distill_kl.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output checkpoint_0.667_ffn_distill/ --resume pretrainmodel/swin_t_0.667_ffn.pt  --batch-size 128 --tag lr3e-5_wodrop_kl --opts TRAIN.EPOCHS 30 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none TRAIN.DISTILL_RATIO 0.05
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_deit.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output deit/checkpoint_0.5_ffn/ --resume pretrainmodel/deit_tiny_0.5_ffn.pt  --batch-size 256 --tag lr1.5e-4_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1.5e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_deit.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output deit/checkpoint_0.5_ffn/ --resume pretrainmodel/deit_tiny_0.5_ffn.pt  --batch-size 256 --tag lr2e-4_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 2e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341 main_sparse_s_attn.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_sparseattn_0.8_100/  --opts TRAIN.EPOCHS 10  TRAIN.WARMUP_EPOCHS 2 DATA.BATCH_SIZE 64
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341 main_sparse_s_ffn.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_sparseffn_0.8_100/  --opts TRAIN.EPOCHS 10  TRAIN.WARMUP_EPOCHS 2 DATA.BATCH_SIZE 64
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_sparse_s_attn.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_sparse_s_attn_0.1_100/ --resume pretrainmodel/swin_tiny_patch4_window7_224.pth  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none MODEL.DROP_PATH_RATE 0.0 TRAIN.SPARSE_RATIO 0.1
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_sparse_s_attn.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_sparse_s_attn_0.2_100/ --resume pretrainmodel/swin_tiny_patch4_window7_224.pth  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none MODEL.DROP_PATH_RATE 0.0 TRAIN.SPARSE_RATIO 0.2
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_sparse_s_attn.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_sparse_s_attn_0.3_100/ --resume pretrainmodel/swin_tiny_patch4_window7_224.pth  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none MODEL.DROP_PATH_RATE 0.0 TRAIN.SPARSE_RATIO 0.3

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_sparse_s_ffn.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_sparse_s_ffn_0.1_100/ --resume pretrainmodel/swin_tiny_patch4_window7_224.pth  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none MODEL.DROP_PATH_RATE 0.0 TRAIN.SPARSE_RATIO 0.1
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_sparse_s_ffn.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_sparse_s_ffn_0.2_100/ --resume pretrainmodel/swin_tiny_patch4_window7_224.pth  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none MODEL.DROP_PATH_RATE 0.0 TRAIN.SPARSE_RATIO 0.2
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12341  main_sparse_s_ffn.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_sparse_s_ffn_0.3_100/ --resume pretrainmodel/swin_tiny_patch4_window7_224.pth  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none MODEL.DROP_PATH_RATE 0.0 TRAIN.SPARSE_RATIO 0.3
# sleep 2.5h
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12342  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pca_wo_lastblock_ft2k.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.3
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12342  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pca_wo_lastblock_ft2k.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.2
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12342  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pca_wo_lastblock_ft2k.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.1
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12343  main_ratio_ffn_swin_distill_kl.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca_distill/ --resume swin_pac_model/swin_pca_wo_lastblock_ft2k.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 TRAIN.DISTILL_RATIO 0.5
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12343  main_ratio_ffn_swin_distill_kl.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca_distill/ --resume swin_pac_model/swin_pca_wo_lastblock_ft2k.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 TRAIN.DISTILL_RATIO 1.0
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12343  main_ratio_ffn_swin_distill_kl.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca_distill/ --resume swin_pac_model/swin_pca_wo_lastblock_ft2k.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 TRAIN.DISTILL_RATIO 2.0
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12342  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pca_wo_lastblock_ft2k.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.6
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12342  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pca_wo_lastblock_ft2k.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.5
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12342  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pca_wo_lastblock_ft2k.pth  --batch-size 64 --tag lr3e-5 --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.4

# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12343  main_ratio_ffn_swin_distill.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca_distill/ --resume swin_pac_model/swin_pac_16_all_uvb_merge_wo_lastblock.pth  --batch-size 64 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 TRAIN.ACCUMULATION_STEPS 2 TRAIN.DISTILL_RATIO 0.03
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12343  main_ratio_ffn_swin_distill.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca_distill/ --resume swin_pac_model/swin_pac_16_all_uvb_merge_wo_lastblock.pth  --batch-size 64 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 TRAIN.ACCUMULATION_STEPS 2 TRAIN.DISTILL_RATIO 0.05
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12343  main_ratio_ffn_swin_distill.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca_distill/ --resume swin_pac_model/swin_pac_16_all_uvb_merge_wo_lastblock.pth  --batch-size 64 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 TRAIN.ACCUMULATION_STEPS 2 TRAIN.DISTILL_RATIO 0.1
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12344  main_ratio_ffn_deit.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output deit/checkpoint_baseline_50/  --batch-size 256 --tag lr1e-3 --opts TRAIN.EPOCHS 50 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-3  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.05 
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12344  main_ratio_ffn_deit_enlarge.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output deit/checkpoint_enlarge_ffn_50/  --batch-size 256 --tag lr1e-3 --opts TRAIN.EPOCHS 50 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-3  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.05 
# sleep 2h
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12343  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pac_16_all_uvb_merge_wo_lastblock.pth  --batch-size 64 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12343  main_ratio_ffn_swin1.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pac_16_all_uvb_merge_wo_lastblock.pth  --batch-size 64 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01

# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12343  main_ratio_ffn_swin.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output swin/checkpoint_0.5_ffn_pca/ --resume swin_pac_model/swin_pac_16_all_uvb_merge_wo_lastblock.pth  --batch-size 64 --tag lr5e-6_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-6  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12345  main_ratio_ffn_resmlp_distill_kl.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_distill/ --resume pretrainmodel/resmlp_12_no_dist_0.5_ffn.pt  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 100 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none TRAIN.DISTILL_RATIO 0.05
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_resmlp_distill_kl.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_distill/ --resume pretrainmodel/resmlp_12_no_dist_0.5_ffn.pt  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none TRAIN.DISTILL_RATIO 0.05
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_resmlp_distill_kl.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_0.5_ffn_distill/ --resume pretrainmodel/resmlp_12_no_dist_0.5_ffn.pt  --batch-size 128 --tag lr5e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none TRAIN.DISTILL_RATIO 0.1
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_distill.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output checkpoint_0.75_ffn_distill/ --resume pretrainmodel/swin_t_0.75_ffn.pt  --batch-size 128 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none TRAIN.DISTILL_RATIO 0.01
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_distill.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output checkpoint_0.75_ffn_distill/ --resume pretrainmodel/swin_t_0.75_ffn.pt  --batch-size 128 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none TRAIN.DISTILL_RATIO 0.05
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_distill.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output checkpoint_0.75_ffn_distill/ --resume pretrainmodel/swin_t_0.75_ffn.pt  --batch-size 128 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none TRAIN.DISTILL_RATIO 0.1
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_distill.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output checkpoint_0.75_ffn_distill/ --resume pretrainmodel/swin_t_0.75_ffn.pt  --batch-size 128 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none TRAIN.DISTILL_RATIO 0.5
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12345  main_ratio_ffn_distill.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output checkpoint_0.75_ffn_distill/ --resume pretrainmodel/swin_t_0.75_ffn.pt  --batch-size 128 --tag lr3e-5_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 AUG.AUTO_AUGMENT none TRAIN.DISTILL_RATIO 1.0
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12343  main_ratio_ffn_deit_enlarge.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_mask_weight/ --resume pretrainmodel/resmlp_12_no_dist.pth  --batch-size 256 --tag lr1e-4_wodrop --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 --amp-opt-level O0
# CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node 8 --master_port 12343  main_ratio_ffn_deit_enlarge.py --cfg configs/swin_tiny_patch4_window7_224.yaml --data-path /mnt/ramdisk2/ImageNet/ --output resmlp_12/checkpoint_mask_weight/ --resume pretrainmodel/resmlp_12_no_dist.pth  --batch-size 256 --tag lr1e-4_wodrop --opts TRAIN.EPOCHS 50 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 --amp-opt-level O0