CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking_ft.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_t/  --batch-size 128 --tag lr1e-5_alldata --resume deit/ffn_output/all_fc_ada/deit_t/deit_t_pca_all_uvb_fewshot2_0.33_merge_ada.pth --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0 AUG.AUTO_AUGMENT none
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking_ft.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_t/  --batch-size 128 --tag lr1e-5_alldata --resume deit/ffn_output/all_fc_ada/deit_t/deit_t_pca_all_uvb_fewshot2_0.33_merge_ada.pth --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0 AUG.AUTO_AUGMENT none
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking_ft.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_t/  --batch-size 128 --tag lr1e-5_alldata --resume deit/ffn_output/all_fc_ada/deit_t/deit_t_pca_all_uvb_fewshot2_0.33_merge_ada.pth --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 8e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0 AUG.AUTO_AUGMENT none
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking_ft.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_t/  --batch-size 128 --tag lr1e-5_alldata --resume deit/ffn_output/all_fc_ada/deit_t/deit_t_pca_all_uvb_fewshot2_0.33_merge_ada.pth --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0 AUG.AUTO_AUGMENT none
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking_ft.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_t/  --batch-size 128 --tag lr1e-5_alldata --resume deit/ffn_output/all_fc_ada/deit_t/deit_t_pca_all_uvb_fewshot2_0.33_merge_ada.pth --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0 AUG.AUTO_AUGMENT none
CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking_ft.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_t/  --batch-size 128 --tag lr1e-5_alldata --resume deit/ffn_output/all_fc_ada/deit_t/deit_t_pca_all_uvb_fewshot2_0.33_merge_ada.pth --opts TRAIN.EPOCHS 10 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0 AUG.AUTO_AUGMENT none

# CUDA_VISIBLE_DEVICES=4,5,6 python -m torch.distributed.launch --nproc_per_node 3 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 96 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed37.9_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6 python -m torch.distributed.launch --nproc_per_node 3 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 96 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed37.9_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6 python -m torch.distributed.launch --nproc_per_node 3 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 96 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed37.9_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6 python -m torch.distributed.launch --nproc_per_node 3 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 96 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed37.9_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 8e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6 python -m torch.distributed.launch --nproc_per_node 3 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 96 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed37.9_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40

# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 64 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed40.3_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 8e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 64 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed40.3_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 64 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed40.3_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 64 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed40.3_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-4  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 64 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed40.3_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 8e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 64 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed40.3_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 5e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 64 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed40.3_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 3e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40
# CUDA_VISIBLE_DEVICES=4,5,6,7 python -m torch.distributed.launch --nproc_per_node 4 --master_port 12341  main_deit_feature_mimicking.py --cfg configs/swin_base_patch4_window7_224.yaml --data-path /mnt/ramdisk/ImageNet/ --output deit/checkpoint_pca_all_mimicking_b/  --batch-size 64 --tag speed40.3 --resume deit/ffn_output/all_fc_ada/deit_b/deit_b_pca_all_uvb_fewshot2_speed40.3_merge_ada.pth --opts TRAIN.EPOCHS 1000 TRAIN.WARMUP_EPOCHS 2 TRAIN.BASE_LR 1e-5  TRAIN.MIN_LR 1e-6 TRAIN.WEIGHT_DECAY 0.01 MODEL.DROP_PATH_RATE 0.0  SAVE_FREQ 40